# Copy the front-end sources into the backend so that one Render service can
# serve both the API and the pages (same origin, no CORS).
#
# Usage (from the repository root), PowerShell 7 recommended:
#   pwsh -File deploy/sync-frontend.ps1
#
# Adjust the source path when the two repositories are not siblings.
#
# Besides copying the client, the script writes src/web/index.html. That file is
# generated rather than copied because the client entry point is calculator.html:
# without an index.html the deployed root path "/" would show the JSON endpoint
# list instead of the calculator, and the app would not register its static
# routes at all. See DEPLOYMENT.md section 2.

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$target = Join-Path $repoRoot 'src\web'
$candidates = @(
    (Join-Path (Split-Path -Parent $repoRoot) '832402226_calculator_frontend\src'),
    (Join-Path $repoRoot '..\832402226_calculator_frontend\src')
)
$source = $candidates | Where-Object { Test-Path (Join-Path $_ 'calculator.html') } | Select-Object -First 1

if (-not $source) {
    Write-Error "Front-end sources not found. Checked: $($candidates -join ', ')"
}

# Rebuild the target from scratch so that files deleted in the front-end also
# disappear here. -LiteralPath is used because the path can contain characters
# such as [ ] that a wildcard based cmdlet would try to interpret, and the
# directory itself is removed before being recreated; if a stale file is locked,
# the copy below still refreshes everything else with -Force.
if (Test-Path -LiteralPath $target) {
    Remove-Item -LiteralPath $target -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $target | Out-Null
Copy-Item -Path (Join-Path $source '*') -Destination $target -Recurse -Force

# Entry page. A meta refresh needs no JavaScript and keeps the browser URL on the
# clean root path, because the redirect happens before the app script runs.
# Single quoted here-string: nothing is interpolated, so the CSS braces and the
# inline script stay exactly as written.
$indexHtml = @'
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="color-scheme" content="light" />
    <meta name="theme-color" content="#EDDBC7" />
    <meta name="robots" content="noindex" />
    <title>832402226 Calculator</title>
    <link rel="icon" href="data:," />
    <!-- Generated by deploy/sync-frontend.ps1 - do not edit by hand. -->
    <meta http-equiv="refresh" content="0; url=./calculator.html" />
    <style>
      body {
        margin: 0;
        min-height: 100vh;
        display: flex;
        align-items: center;
        justify-content: center;
        background: #EDDBC7;
        color: #4A3B32;
        font: 16px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif;
      }
      main { text-align: center; padding: 24px; }
      a { color: #8C5A3C; }
    </style>
  </head>
  <body>
    <main>
      <p id="note">Loading the calculator&hellip; / 正在打开计算器&hellip;</p>
      <p><a href="./calculator.html">Open the calculator / 打开计算器</a></p>
    </main>
    <script>
      window.location.replace('./calculator.html');
    </script>
  </body>
</html>
'@

# UTF8Encoding($false) writes without a byte order mark, which is what browsers
# expect for HTML.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $target 'index.html'), $indexHtml, $utf8NoBom)

$count = (Get-ChildItem $target -Recurse -File).Count
Write-Host "Front-end copied into $target ($count files, index.html generated)."
Write-Host 'Remember to commit src/web before deploying.'